### ISSUE TITLE
ProjectorRays attribution

### ISSUE THREAD

**Issue by djsrv** [igorlira/dirplayer-rs#3]
A fair bit of code here seems to be ported to Rust from [ProjectorRays](https://github.com/ProjectorRays/ProjectorRays). Could you please include it in the acknowledgements?

Also, nice to see Habbo running on the modern web!

**Comment by igorlira** [comment]
Yes, thank you for pointing out! ProjectorRays was essential to putting this project together and I feel bad for missing it in the acknowledgements. I just sent a commit updating the README with it.
