### ISSUE TITLE
RuntimeError: unreachable

### ISSUE THREAD

**Issue by fripokoff** [igorlira/dirplayer-rs#4]
Hello can you tell me why I'm getting this error? I'm in localhost and I'm trying to connect to online servers.

```
vm_rust.js:1014 Lingo parse error:  --> 1:1
  |
1 | core
  | ^---
  |
  = expected expr
vm_rust.js:1017 execute_task #4 url: external_variables.txt?41100 resolved: http://localhost:3000/dcr/external_variables.txt?41100
vm_rust.js:1017 execute_task #5 url: external_texts.txt?41523 resolved: http://localhost:3000/dcr/external_texts.txt?41523
vm_rust.js:1014 Lingo parse error:  --> 1:1
  |
1 | core
  | ^---
  |
  = expected expr
```

**Comment by igorlira** [comment]
The Lingo parsing errors on your log are normal and won't crash the player. If you're getting a `RuntimeError: unreachable` error, check your console log for the full error message, where it should tell the line in which the error happened, then paste it here so we can diagnose further

**Comment by fripokoff** [comment]
With your update it's working fine but I'm stopped at this place in fact I see the sulake appear 2 seconds then it disappears and black screen.I'm trying to load habbo origins to be able to play in a recent browser.

![image](https://github.com/igorlira/dirplayer-rs/assets/65672472/d2e2a425-0847-47df-bf86-2fc60aba45e0)

**Comment by igorlira** [comment]
@fripokoff Can you check that the line endings on your external_*.txt are CRLF? You can check and convert in the VSCode bottom bar

**Comment by fripokoff** [comment]
I did it, but it didn't work. It's in CRLF.
